-- ================================================================
-- CommOS — Seed 136 real communications (Jan–Apr 2026)
-- Run AFTER 001_initial_schema.sql
-- ================================================================
insert into communications (id, titulo, date, pais, canal, segmento, ubicacion, topico, formato, idioma, alcance, estado, destacado) values
(1,'Cambio organizacional Controlling','2026-01-02','{"AR","MX","CL","PE","BR","ES","CN"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Org"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(2,'Sueldos','2026-01-04','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(3,'Healthy week','2026-01-05','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Bienestar"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',true),
(4,'Ingresos y promociones','2026-01-06','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(5,'Kits escolares','2026-01-07','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Campaña"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',true),
(6,'PEM:Objetivos reminder','2026-01-08','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Gestión"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(7,'Proveedores','2026-01-09','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Org"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',true),
(8,'Analista HR','2026-01-07','{"AR"}','{"LinkedIn"}','{"Staff"}','{"Operaciones"}','{"Talento"}','{"Post"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(9,'Búsqueda VCM','2026-01-08','{"AR"}','{"LinkedIn"}','{"Staff"}','{"Operaciones"}','{"Talento"}','{"Post"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(10,'Día de Reyes','2026-01-10','{"MX"}','{"LinkedIn"}','{"Tiendas Isadora"}','{"Operaciones"}','{"Campaña"}','{"Post"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(11,'Día de Reyes','2026-01-10','{"MX"}','{"Humand"}','{"Tiendas Isadora"}','{"Oficina"}','{"Campaña"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(12,'Estrategia proveedores','2026-01-13','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Org"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(13,'PEM reminder','2026-01-14','{"AR"}','{"Emarsys"}','{"Staff Retail"}','{"Oficina"}','{"Gestión"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(14,'Nacimiento','2026-01-15','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',true),
(15,'Evaluación 2025','2026-01-19','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Gestión"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(16,'Flexibilidad','2026-01-21','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(17,'Helados','2026-01-22','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Beneficios"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(18,'Post in blue PIB: Planning ISA','2026-01-23','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Talento"}','{"Email"}','{"Español"}','{"Local"}','{"En revisión"}',false),
(19,'Apertura Perú','2026-01-24','{"AR"}','{"LinkedIn"}','{"Staff"}','{"Operaciones"}','{"Marca"}','{"Post"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(20,'TikTok Chile','2026-01-28','{"CL"}','{"TikTok"}','{"Tiendas Isadora"}','{"Operaciones"}','{"Campaña"}','{"Video"}','{"Español"}','{"Local"}','{"En revisión"}',true),
(21,'Summer','2026-01-29','{"AR"}','{"LinkedIn"}','{"Staff"}','{"Operaciones"}','{"Cultura"}','{"Post"}','{"Español"}','{"Local"}','{"Aprobado"}',true),
(22,'Objetivos 2026','2026-01-30','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Gestión"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(23,'Frutas','2026-02-02','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Beneficios"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',true),
(24,'Hello Kitty','2026-02-03','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Campaña"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',true),
(25,'Estrategia proveedores','2026-02-04','{"AR","MX","CL","PE","BR","ES","CN"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Org"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(26,'Back to school','2026-02-05','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Campaña"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',true),
(27,'Cambios ecommerce','2026-02-02','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Org"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',true),
(28,'Hitazos teaser','2026-02-03','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Innovación"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',true),
(29,'Ingresos y movimientos','2026-02-04','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',true),
(30,'Evaluación febrero','2026-02-05','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Gestión"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(31,'ISA Rouen','2026-02-06','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',true),
(32,'San Valentín','2026-02-09','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Campaña"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',true),
(33,'Hitazos','2026-02-10','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Innovación"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',true),
(34,'PIB Visual','2026-02-13','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Talento"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(35,'PIB Global Buyer','2026-02-11','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Talento"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(36,'Team San Valentín','2026-02-12','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Campaña"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',true),
(37,'Paro nacional','2026-02-18','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',true),
(38,'Curso VM','2026-02-19','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Formación"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(39,'Guardería','2026-02-20','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',true),
(40,'PEM Evaluación última semana','2026-02-23','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Gestión"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(41,'PIB BI','2026-02-24','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Talento"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(42,'Cumpleaños','2026-02-26','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',true),
(43,'Recap acción social','2026-02-27','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Operaciones"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',true),
(44,'Búsqueda Controlling','2026-02-24','{"AR"}','{"LinkedIn"}','{"Staff"}','{"Operaciones"}','{"Talento"}','{"Post"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(45,'Oficina frutas','2026-03-02','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Beneficios"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(46,'Ingresos y movimientos','2026-03-03','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(47,'Día de la mujer global','2026-03-04','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"DEI"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',true),
(48,'Curso LMS VICO','2026-03-05','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Innovación"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',true),
(49,'Encuesta WAG','2026-03-06','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Escucha"}','{"Encuesta"}','{"Español"}','{"Global"}','{"Aprobado"}',true),
(50,'Lanzamiento VICO','2026-03-02','{"AR"}','{"Emarsys"}','{"Tiendas Isadora"}','{"Oficina"}','{"Innovación"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(51,'Spoiler VICO','2026-03-03','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Innovación"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',true),
(52,'PIB gestor inventarios','2026-03-05','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Talento"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(53,'Valor KM','2026-03-06','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(54,'Sueldos','2026-03-02','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(55,'Coffee Club','2026-03-05','{"AR"}','{"Emarsys"}','{"Tiendas Isadora"}','{"Oficina"}','{"Marca"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(56,'Coffee Club','2026-03-05','{"AR"}','{"Humand"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',true),
(57,'Encuesta WAG','2026-03-06','{"GL"}','{"Humand"}','{"Staff"}','{"Oficina"}','{"Escucha"}','{"Encuesta"}','{"Español"}','{"Global"}','{"Aprobado"}',true),
(58,'Búsqueda HR','2026-03-05','{"AR"}','{"LinkedIn"}','{"Staff"}','{"Operaciones"}','{"Talento"}','{"Post"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(59,'Food market','2026-03-09','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(60,'Workshop VICO','2026-03-10','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Innovación"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(61,'Hitazos teaser','2026-03-11','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Innovación"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(62,'Acción 8M','2026-03-12','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"DEI"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(63,'Bimbo','2026-03-17','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Beneficios"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',true),
(64,'Nacimiento','2026-03-18','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(65,'Campaña VICO','2026-03-19','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Innovación"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(66,'Fundación Ruta 40','2026-03-20','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',true),
(67,'Recap campaña VICO','2026-03-26','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Innovación"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(68,'PEM: Evaluación feedback','2026-03-28','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Gestión"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(69,'Cierre mes mujer','2026-03-30','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"DEI"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',true),
(70,'Cumpleaños','2026-03-31','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(71,'Aniversario BSG','2026-03-30','{"AR"}','{"LinkedIn"}','{"Staff"}','{"Operaciones"}','{"Talento"}','{"Post"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(72,'Hitazos video','2026-04-01','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Innovación"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(73,'Sueldos','2026-04-01','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(74,'Reconocimiento TM','2026-04-01','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(75,'Hitazos reconocimiento Todomoda','2026-04-01','{"AR"}','{"Humand"}','{"Staff"}','{"Oficina"}','{"Innovación"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',true),
(76,'Semana de la salud','2026-04-06','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Bienestar"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',true),
(77,'Apertura Isadora Armenia','2026-04-06','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Marca"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',true),
(78,'Apertura Isadora Armenia','2026-04-06','{"AR"}','{"Humand"}','{"Staff"}','{"Oficina"}','{"Marca"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',true),
(79,'Apertura Isadora Armenia','2026-04-06','{"AR"}','{"LinkedIn"}','{"Staff"}','{"Operaciones"}','{"Marca"}','{"Post"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(80,'Culture Week teaser','2026-04-07','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(81,'Ingresos y movimientos','2026-04-07','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(82,'Interacción CW innovación','2026-04-07','{"GL"}','{"Humand"}','{"Staff"}','{"Oficina"}','{"Innovación"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(83,'Global Meeting evento','2026-04-07','{"GL"}','{"Humand"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(84,'Apertura Isadora Armenia','2026-04-07','{"AR"}','{"LinkedIn"}','{"Staff"}','{"Operaciones"}','{"Marca"}','{"Post"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(85,'Ruidos oficina mejoras','2026-04-08','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(86,'Charla nutrición','2026-04-08','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Bienestar"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(87,'Evaluación feedback LMS','2026-04-08','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Gestión"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(88,'Hitazos oficina','2026-04-08','{"GL"}','{"TikTok"}','{"Staff"}','{"Operaciones"}','{"Innovación"}','{"Video"}','{"Español"}','{"Global"}','{"Aprobado"}',true),
(89,'Se viene Culture Week','2026-04-09','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(90,'Beneficios saludables','2026-04-09','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Bienestar"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(91,'PIB SEM','2026-04-09','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Talento"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(92,'Primeros auxilios','2026-04-10','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(93,'Recap semana salud','2026-04-10','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Bienestar"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(94,'Ganadores challenge VICO','2026-04-10','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Innovación"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(95,'Recap semana salud','2026-04-10','{"GL"}','{"Humand"}','{"Staff"}','{"Oficina"}','{"Bienestar"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(96,'Semana salud recap','2026-04-10','{"AR"}','{"LinkedIn"}','{"Staff"}','{"Operaciones"}','{"Bienestar"}','{"Post"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(97,'Nacimiento Augusto','2026-04-13','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',true),
(98,'Global meeting reminder','2026-04-13','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',true),
(99,'Bimbo','2026-04-14','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Beneficios"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(100,'Nuevo aprendizaje','2026-04-14','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Formación"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(101,'Perú ATEC','2026-04-14','{"AR"}','{"LinkedIn"}','{"Staff"}','{"Operaciones"}','{"Talento"}','{"Post"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(102,'Visita Georgalos','2026-04-15','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Beneficios"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(103,'Culture Week: agenda','2026-04-15','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(104,'Curso gestión caja','2026-04-15','{"AR"}','{"Emarsys"}','{"TM"}','{"Oficina"}','{"Formación"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(105,'Visual merchandising','2026-04-15','{"AR"}','{"Humand"}','{"Staff"}','{"Oficina"}','{"Talento"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(106,'Culture week cápsula','2026-04-16','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(107,'Visual merchandising','2026-04-16','{"AR"}','{"Humand"}','{"Staff"}','{"Oficina"}','{"Talento"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(108,'Apertura Isadora Armenia','2026-04-16','{"AR"}','{"LinkedIn"}','{"Staff"}','{"Operaciones"}','{"Marca"}','{"Post"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(109,'Culture week speakers','2026-04-17','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(110,'Encuesta global meeting','2026-04-17','{"GL"}','{"Humand"}','{"Staff"}','{"Oficina"}','{"Escucha"}','{"Encuesta"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(111,'Evento CW reminder','2026-04-20','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(112,'Evento CW hoy','2026-04-21','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(113,'PEM bono','2026-04-21','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Gestión"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(114,'Dinámicas virtuales','2026-04-22','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Org"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(115,'Charla Rafa','2026-04-22','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(116,'Culture week día 1','2026-04-22','{"AR"}','{"Humand"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(117,'Video innovación','2026-04-23','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Innovación"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(118,'JIRA','2026-04-23','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Innovación"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',true),
(119,'Culture week día 2','2026-04-23','{"AR"}','{"Humand"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(120,'Charla Fredi Vivas','2026-04-24','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(121,'Capacitaciones LMS','2026-04-24','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Formación"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',true),
(122,'Culture week día 3','2026-04-24','{"AR"}','{"Humand"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(123,'Se viene JIRA','2026-04-27','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Innovación"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',true),
(124,'PIB SEM','2026-04-27','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Talento"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(125,'Revive las charlas','2026-04-27','{"GL"}','{"Humand"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',false),
(126,'Recap CW','2026-04-27','{"GL"}','{"Humand"}','{"Staff"}','{"Oficina"}','{"Operaciones"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',true),
(127,'Recap CW encuesta','2026-04-28','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Escucha"}','{"Encuesta"}','{"Español"}','{"Global"}','{"Aprobado"}',true),
(128,'Culture week tiendas','2026-04-28','{"AR"}','{"Humand"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(129,'Culture Week multi canal','2026-04-28','{"GL"}','{"Instagram"}','{"Staff"}','{"Operaciones"}','{"Cultura"}','{"Post"}','{"Español"}','{"Global"}','{"Aprobado"}',true),
(130,'Hola Jira','2026-04-29','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Innovación"}','{"Email"}','{"Español"}','{"Global"}','{"Aprobado"}',true),
(131,'VICO Nacho','2026-04-29','{"GL"}','{"Humand"}','{"Staff"}','{"Oficina"}','{"Innovación"}','{"Email"}','{"Español"}','{"Global"}','{"En revisión"}',true),
(132,'Cumpleaños','2026-04-30','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(133,'Mejoras oficina','2026-04-30','{"AR"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Cultura"}','{"Email"}','{"Español"}','{"Local"}','{"Aprobado"}',false),
(134,'Se viene Blumi','2026-04-30','{"GL"}','{"Emarsys"}','{"Staff"}','{"Oficina"}','{"Innovación"}','{"Email"}','{"Español"}','{"Global"}','{"En revisión"}',true),
(135,'Se viene Blumi','2026-04-30','{"GL"}','{"Humand"}','{"Staff"}','{"Oficina"}','{"Innovación"}','{"Email"}','{"Español"}','{"Global"}','{"En revisión"}',true),
(136,'Belu Barrague','2026-04-30','{"AR"}','{"LinkedIn"}','{"Staff"}','{"Operaciones"}','{"Org"}','{"Post"}','{"Español"}','{"Local"}','{"En revisión"}',false);

-- Reset sequence
select setval('communications_id_seq', 136);
